[graph]
all-features = true

[advisories]
version = 2
yanked = "deny"

[licenses]
version = 2
confidence-threshold = 1.0
allow = [
    "Apache-2.0",
    "GPL-3.0",
    "MIT",
    "Unicode-3.0"
]

[sources]
unknown-registry = "deny"
